ansible_host: ENC[AES256_GCM,data:oHxQ5aFy+xaa46E=,iv:ayKDP+dcgZ4kh8kRZdAfDkd8uNueLXxBT5z1WTcLzZo=,tag:/p5KQLE+Qb4kaH1lI5pytg==,type:str]
ansible_user: ENC[AES256_GCM,data:ltBisVc=,iv:w+8b30jHtf+/MuyVRqAEjNq8e/Cux5l9bc1eq6/sFng=,tag:2rLQJ06ECvuksYybfB/kdA==,type:str]
#ENC[AES256_GCM,data:KgsWXmk//EvOdhmV57atsoSzB+FjrvVx3AXmJ24=,iv:jXeLyP+bPJSCbVV/EDbMCZpE9hhaPi4vzN0NsPlXDXg=,tag:9x0pAyeRfosXWJ9UHUbxZQ==,type:comment]
node_stack_dockhand_url: ENC[AES256_GCM,data:sQpyTDh6zu07CqR4cVqHYkadVZmljpM3IWN6VnG7LrAKvV9tIHLoyA==,iv:i4RMd2vR/CnDccROtdG2SNYFhkWvmbNQWY3JMqDtI4g=,tag:6PRxxm/oadvNGfslJd/Jeg==,type:str]
node_stack_dockhand_token: ENC[AES256_GCM,data:m0ibTVafxrnRrl7dk75YWvVRfwqBRti1ox0AOy/BrizX0uZPNF/Md1AggQ==,iv:prlPHPMZ+ZtiZHN3nrPYFUzqG8fA71/Fz67eZOBQw08=,tag:NwuNxdKEW4Y3IGGdIq0FIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWjQxVW5IS21ocUl4M1dQ
            ZllXbzI5dGl2M1pKWERZbnhTSmp5TjRaVkJzCmRpQUU2YjdMQzNnTzJMMlhxL1h5
            ZFRDeVQ0VGNWYm5xUFEyMDhQanlvU1UKLS0tIC93MVdic1BFaTBGRkR1ZUtZYmJB
            MzZHUXVTU1RGQS95L2htbk8yK0l4QzAKkoziDzEJsTzNIl48V5ujh8P9mIg+MMtZ
            wF4p15XFgGVFa0v3BAv1HLLHPM4ddYF9tcoRaHl4HbJJTpgctqcwnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-28T19:47:29Z"
    mac: ENC[AES256_GCM,data:LQCbu4RSlW8IoOxDZvS1Qu+yF34pTJv81SxG6QTfsOP+LsDIoBNyKB5X+RInT2EfYi+SfSbEgkX6rMpEejofIbxYRwgUX64/FiwwJoUth6AnPpkwQbkITsPZmU1uLiGEOrh1/DDSEzpNCGQpouxDIt4w28TSS5ROr58/jGUkpQY=,iv:mF5tLFt+7tJBYAOki1mmO3OOmEtf6Ur6PGxZJnzl6GE=,tag:40HdMrO9Y1v7N/zr7Q40qQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
