ansible_host: ENC[AES256_GCM,data:oHxQ5aFy+xaa46E=,iv:ayKDP+dcgZ4kh8kRZdAfDkd8uNueLXxBT5z1WTcLzZo=,tag:/p5KQLE+Qb4kaH1lI5pytg==,type:str]
ansible_user: ENC[AES256_GCM,data:ltBisVc=,iv:w+8b30jHtf+/MuyVRqAEjNq8e/Cux5l9bc1eq6/sFng=,tag:2rLQJ06ECvuksYybfB/kdA==,type:str]
node_stack_obs_host: ENC[AES256_GCM,data:lTRxRMN5LTE=,iv:MWvIhan+HdKbS7elpj/sDjtRcfzmRfCmPfRTniEedA8=,tag:qnlacft5ffBJlF60eBbX+g==,type:str]
node_stack_dockhand_url: ENC[AES256_GCM,data:KRFOa+T/rwkykQd567pMDopKyKY=,iv:phh5VcLqiGm/WMjf3x7AsmWzvP7Vmg/8QW3CAugMXuk=,tag:qVUbbCR2L9Ag1u85PLAldQ==,type:str]
node_stack_dockhand_token: ENC[AES256_GCM,data:l/gFcWeO4oI=,iv:2K/TLeTRBybiySUuUo76SnfoEQ4TPkCiK0DWMSIXovI=,tag:u1ZGJcU08SWeASpvz6MWnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWjQxVW5IS21ocUl4M1dQ
            ZllXbzI5dGl2M1pKWERZbnhTSmp5TjRaVkJzCmRpQUU2YjdMQzNnTzJMMlhxL1h5
            ZFRDeVQ0VGNWYm5xUFEyMDhQanlvU1UKLS0tIC93MVdic1BFaTBGRkR1ZUtZYmJB
            MzZHUXVTU1RGQS95L2htbk8yK0l4QzAKkoziDzEJsTzNIl48V5ujh8P9mIg+MMtZ
            wF4p15XFgGVFa0v3BAv1HLLHPM4ddYF9tcoRaHl4HbJJTpgctqcwnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-28T09:18:12Z"
    mac: ENC[AES256_GCM,data:BL+qBWkqbmU/D5oRrbqfdzXEOq7KMGlCxcS4tgAKzKMamgyUBt1V1vDCEVVcasEvC8qUwwAJ4c6EIsiJtHtkindAURDw5eLDRPIzYB95nFR7++g1ehsAuiQxm3YwKHVxUCqe4PUPVv1zTQ38v4qys5570HTvKSgI2dNenSvGNmc=,iv:Bckb0ZDx3zq0sWEk3qmia89LcpTdt4fB7okkE7gFBCI=,tag:67vjS8pWrSlENr3qXwpkWA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
