# Bootstrap
# hostname_enabled: true

# Shell
motd_enabled: false
dotfiles_enabled: false

# Unattended upgrades
unattended_upgrades_enabled: true
# unattended_upgrades_blacklist: []
# unattended_upgrades_skip_reboot_required: false
unattended_upgrades_auto_reboot: false
# unattended_upgrades_auto_reboot_time: "04:00"

# Swap
# swap_enabled: false
# swap_size: "2G"

# Firewall
# ufw_enabled: false
# ufw_extra_rules:
#   - { rule: allow, port: 8080, proto: tcp, comment: "Web" }

# Docker
# docker_enabled: true

# Cron
# cron_enabled: true
# cron_docker_prune: true
# cron_extra_jobs: []

# Node agent
node_stack_alloy_enabled: true
node_stack_hawser_enabled: true
node_stack_bifrost_enabled: false
node_stack_backrest_enabled: false
