- name: Restart komodo_periphery
  community.docker.docker_compose_v2:
    project_src: "{{ komodo_periphery_deploy_path }}"
    state: restarted
    remove_orphans: true
  ignore_errors: "{{ ansible_check_mode }}"
