ansible_host: ENC[AES256_GCM,data:+6mvEnNSdsqmn70=,iv:JENf6UVOHM8Y3ZkAUyIOrCWZC73EJ+dWuHiiX7akfl0=,tag:iFFHco6GTzNCpCKBzcsQbw==,type:str]
ansible_user: ENC[AES256_GCM,data:Lc6V5WE=,iv:C1wWpSgZRNFumrORo9DF/paLshgNLBVmzvH413I60I8=,tag:N1i+8jgnbf28eKoxz9j5CA==,type:str]
node_stack_obs_host: ENC[AES256_GCM,data:UlDPDtHb95M=,iv:WjByL45YQV7ZoB1CW//a7OqB5ljhfVGuy2QYdl1geMM=,tag:PR/RFDwrJ188+5CWYB8Mew==,type:str]
node_stack_dockhand_url: ENC[AES256_GCM,data:1v050ULWmrmfCldCksDe9oMD8Wo=,iv:tc7YDAhru2dZvyKTGUsQLtLDT2zXUAJ+KfdsWjxdUsI=,tag:FIENyrKXlP/g//EJXrJOgQ==,type:str]
node_stack_dockhand_token: ENC[AES256_GCM,data:ty3kBPNuzQw=,iv:SNX08VlsLTkaqNUtC6lSk9Lye23R86xQ7Em8ixpO87g=,tag:uogbBhL06FylSS2JweCNNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTzNmSVhNMkRTaHVibDRG
            Q3ZKWXRpL3ZoVHUxRW9pdVM1YVdMS25tRkE4CngwZjNYajdpTGlBSFNZc0F5RG82
            OG1RbzNQdVJQYzUxODljY2QzSWFOc1UKLS0tIFR4TXBlbElma3NBU0krN3M2RERG
            eFRYdzJiUEJPdzM3L2tRZEhHQ3dkb1kK+tjqQ/N4hjTNJD4gT149PzhAqm/+nxiy
            mNiB5FbdOHErKWNgOdkaMnvGn/LH7F6U869eDv9z/ER2/Fn2YmxLAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-28T09:18:13Z"
    mac: ENC[AES256_GCM,data:cUaUmiccxswvh+e7JLYlsMv5q0nDxnTZuMDD25sFxldR1ILAokm95lKCwq790gjnyMqdJMQtybzequXXnblY3AguVsGv3aM3hoXRcXedpu/ZHet+xsVmjQspcITkfKyW7f0EUjP9QtyOQxhG+IrpDvCTm15UAKcivyPo6njlZCA=,iv:ESMCMiH4RLdwfk2lHYMJNno+fobnqPoMLGM4c1F30kQ=,tag:iKTFJZipyZ94vi313O5VIw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
