ansible_host: ENC[AES256_GCM,data:Je7IskT19MMs+0E=,iv:zRw2/QlhErhwqXfgHICjdyxuYKuejoE/cXcfln8hfi8=,tag:A2XxBUDUlysv/6IiLb3JLQ==,type:str]
ansible_user: ENC[AES256_GCM,data:hUAKM2M=,iv:3Gu6M0hSPqWRulFpReLjbsccPBqmvjyjxczi/uc+oLI=,tag:AUHzncW3U7mhRVIwgbNqLQ==,type:str]
node_stack_obs_host: ENC[AES256_GCM,data:XVDHu1cMkxs=,iv:DxrrYoo/9MZIhOkscr1lx3swUslblQ6DWzFnvTr8jhM=,tag:PdDZikP/Kx469xAtjaUhwA==,type:str]
node_stack_dockhand_url: ENC[AES256_GCM,data:FaDei27rbrLS8BVA/BiTsyht2uc=,iv:OPNOmhCfGNBSusTx0EvUHYs46UF1t4s9WMfxpJfqRps=,tag:hvfDkGnu5kMTvrKue0H08Q==,type:str]
node_stack_dockhand_token: ENC[AES256_GCM,data:y2tzIzIUUqw=,iv:XnGM46nfntlU3ZSr0Cl1n8eWr+P3ASDqa4PqTZ0OJG4=,tag:nKvdslTK20o2I325QrFVlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaWR0VlpWRU1rbTg4YTZa
            ZSttbjd6NW12T284Q25ZdGtqMnRZZkhBQjFZClpnS2VPMTVCYURmN293VW9uYWhY
            cXVRVkV2VTVqcVlnSkVIdi9kQUdtcmMKLS0tIDIxbXVSVE1tYzJHZEhNUGhsRDM2
            L25FaHltTjBVbVlTd2tRQW5CcXQ5clUKBICWJaYHluzqkq6SIE38svJlaLjsH6jL
            mnzjAUEy6DZHV+J4pY/M1QRrjC5u5we1zFKCzcqR8Tk6ZyQPQARGgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-28T09:18:13Z"
    mac: ENC[AES256_GCM,data:QCrZ5NA2jybbBi3hykQ3gqJexKqFtSOzr2vjCVtqODMtkhUVpw3l1+jVvhwiuepzNCpdxLDmsEhuraZkWOfy/ZjP7hzUa42xY8etxNrZhCT/KRc4sW1lkVqsdA+3aZyS/MGeBcJSPDRgSEfQy27FBLHR40DWMXTDdak3+kNcAEA=,iv:NwGp2qo4IY9R6vq6nvOmZ6aF/JENJoAvZ92MlOKqpjI=,tag:W5PeGHCLUGOA9qCSWe6M3w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
