ansible_host: ENC[AES256_GCM,data:Je7IskT19MMs+0E=,iv:zRw2/QlhErhwqXfgHICjdyxuYKuejoE/cXcfln8hfi8=,tag:A2XxBUDUlysv/6IiLb3JLQ==,type:str]
ansible_user: ENC[AES256_GCM,data:hUAKM2M=,iv:3Gu6M0hSPqWRulFpReLjbsccPBqmvjyjxczi/uc+oLI=,tag:AUHzncW3U7mhRVIwgbNqLQ==,type:str]
hawser_dockhand_url: ENC[AES256_GCM,data:MfmxsBf+YboCkaGx0/dZRi7iBdc=,iv:U6T0dB4/+9f8gGDFBNGXUEpmBp3r+ymO8Al3AQ8+HZQ=,tag:WKHwmFWj2l/d5U6GxVqMig==,type:str]
hawser_dockhand_token: ENC[AES256_GCM,data:UZEFR5LJwgc=,iv:eMDqUH83m+88ne0w5G9phfUO9kmSSt7qwNlwt/A+uH4=,tag:p75jXixJqKz/fKknBFRyLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaWR0VlpWRU1rbTg4YTZa
            ZSttbjd6NW12T284Q25ZdGtqMnRZZkhBQjFZClpnS2VPMTVCYURmN293VW9uYWhY
            cXVRVkV2VTVqcVlnSkVIdi9kQUdtcmMKLS0tIDIxbXVSVE1tYzJHZEhNUGhsRDM2
            L25FaHltTjBVbVlTd2tRQW5CcXQ5clUKBICWJaYHluzqkq6SIE38svJlaLjsH6jL
            mnzjAUEy6DZHV+J4pY/M1QRrjC5u5we1zFKCzcqR8Tk6ZyQPQARGgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T16:48:31Z"
    mac: ENC[AES256_GCM,data:0J6UQtlhXcCN5PMJpxxl5e5sswKA1JtUzvmUt4rf4ByWF8/KH8gIxtdPU6eqA3xZ/PwMjG1DbYmLyUK7wMn6p00QvQoLgvf0aLaE+kFPqmoOH5UB/y2+OFXrFol9NFnADvu6IZz13eb3vFtnTBRj/jcgFedSHVWyP5c2o4DnnSA=,iv:+L1F38nTykQAKm8rXRxHFlXfJbTHWrPHhq7ITdh/IIw=,tag:Xmva+Zta2YNH5mR9wh6Fdw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
