ansible_host: ENC[AES256_GCM,data:dk0qw8uXTs0q+ixiijbd,iv:sikDB1K5ot+FkNf8vpLopPHjrkpwBl16Ezr7Tk3iMHY=,tag:soBUfdHFweyzdHwePP5ZSg==,type:str]
ansible_user: ENC[AES256_GCM,data:P/KrNic=,iv:epitsXHRcr7s6dEHk3Afd72tVxDS57sTiLWZziLHTQs=,tag:DA097vAEF4MPduW3ZuS1Uw==,type:str]
node_agent_obs_host: ENC[AES256_GCM,data:/2KCEOb+ZXk=,iv:BF2kv7AMk3mrb5RvSCuME9uPAs84Ugx3/9eCKl3W4PQ=,tag:422yyX5eSiu5gyrWTntZMw==,type:str]
node_agent_dockhand_url: ENC[AES256_GCM,data:xZS/drp1htoethiqeqVf5e1ar1c=,iv:vu6zNKwmjtVxoFiTtbGaV4smwrYIGhCPLuwbAgnWAZM=,tag:0x7TZZdapagMOkEUYuBmNQ==,type:str]
node_agent_dockhand_token: ENC[AES256_GCM,data:ctLdqnNKMsg=,iv:PqeGy1bEKu63VNo/Zx7CWYMXX050ohtrWiXAJ+eHKd4=,tag:u3k3uDoSHaqv+gm2EeAxwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdG90c1RTek05NTgxWi9H
            SkRQY250bFNITlpSTUtneTh4bWdITVJOZ2tvCkdGQ2lvcldrcEFBOFhIZDhIc2JZ
            d2YyRkxteTdNOGIrQzdsSnZwYzRqbjgKLS0tICtOTnAyRlhQSEJXb0FrMUUwVlZX
            am5YeUpLSEhKem1uSU9BUytuQ25JV2sKTif9Fhwo2IMlezKskcloYBrZ6CvJwq7h
            2kpkit8ey0C9aJZgWfHngbbBU4qJ2FX4hVQqZiLOcWy5zPs9XvIAWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-27T18:56:37Z"
    mac: ENC[AES256_GCM,data:lemgVb9PsSUGXbk1LkZ1C7yqyAwx5RahP7s+w4KXiG4KkBywk04e0Nc1Uks+gAUzcmL0gwIFhCQy61Qz7sytIbvH+XFja3l9QBchOw2NSm7vwlTA3s2IqYc2DvoNXjvpFaXsEcSihAJdbZnRa7FqtGwUVFejHl3wSC3G2oSGDp8=,iv:sT8CTCc/a+kOpW+0KNzlMzZzjC0nE5zojTE5kT684sw=,tag:8jJt0hne8orgaduLoQIhRw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
