ansible_host: ENC[AES256_GCM,data:udNIz7lFekY1+C9E/af+,iv:nhB6Lb77BVXkV6FFrDd877bjjGtMKvY+YSIP8flmC54=,tag:vVYzkJn/I7NGF+qfk1WLKw==,type:str]
ansible_user: ENC[AES256_GCM,data:gybzsik=,iv:46ezxwJZRl8mX7yV0i3Cd0pNfwX0mEXaLOgK+6bBN9c=,tag:YpjIwUmxBww8yd04wZ5+qw==,type:str]
node_stack_obs_host: ENC[AES256_GCM,data:gF3BDHtSuhk=,iv:m56Sgckfoyaydilf5FUc0EqsLAprcdbmGTWFLkooEQ4=,tag:TCakWNnDaYj7LyxHDWek+Q==,type:str]
node_stack_dockhand_url: ENC[AES256_GCM,data:jbfQCJq3pUQK6j9STD5CffVQZ9w=,iv:hefZg0HVN+jlWAltL4gGFIPgSHCd7p7O8mf08EdmvII=,tag:JX0vEJcyRgD2oVIN44HN1Q==,type:str]
node_stack_dockhand_token: ENC[AES256_GCM,data:NcMXXDbuwh4=,iv:qEMrbgKJBwjwIHKJ80nVDShviBHdZwe/43UMtfVkORQ=,tag:UGtaLGx3Q/VmEKU8LwGKeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dFJHdXU1SmVJbDFlZ1c5
            SHNIWkV3NlpLVXl5aW16UWlHclFuKzkvVnhZCkhreDBTSW4xMC90TmNjWDF5enpq
            QWJIM21sVDVrZzFDY1F6NXkyb2ZSSHMKLS0tIE85ME5FR2xiV2QvanVEWDVSZit5
            dXQrdTU2TFVad3JDMzYybi9janBMTFUK4JcCoJEqGalUFvKb84Q3SXXvdkXblm+B
            vp57cwHhdo/F5+YW6g2dSqfh52rKhMJ3DqgkCLuSo22T6NLsrFuGsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-28T09:18:13Z"
    mac: ENC[AES256_GCM,data:Rmw1/3+aZZ6+GCGJHV14sQ9NG0VQoZZ9lAGizOUw+/PGzbqWIhllmBL2fzjCUkzMimYnkgQYhNSHIqKKVbZQ5xig/AY0mWTB/LThyy3W5nieI+3stEjxL1HjkS0wattTjRrcg+SudsTuzX5tvpk1O7tR+15OBYZcvOk/UHyBWfI=,iv:Yt6Ka2tvVkg9lmfGbUexPPrc1NvArjQ1G35mNh+k2O0=,tag:wYwBAXhue97U5XeSJ6Td1A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
