ansible_host: ENC[AES256_GCM,data:udNIz7lFekY1+C9E/af+,iv:nhB6Lb77BVXkV6FFrDd877bjjGtMKvY+YSIP8flmC54=,tag:vVYzkJn/I7NGF+qfk1WLKw==,type:str]
ansible_user: ENC[AES256_GCM,data:gybzsik=,iv:46ezxwJZRl8mX7yV0i3Cd0pNfwX0mEXaLOgK+6bBN9c=,tag:YpjIwUmxBww8yd04wZ5+qw==,type:str]
hawser_dockhand_url: ENC[AES256_GCM,data:teU9jkXqF65BL3xev7uJArwNBxw=,iv:KmOYO0ybjBvMqFBIOuZQ4eguqj7APQTv8fVH+IUdHwc=,tag:gE7RnASU1sAhaMjhog9/dw==,type:str]
hawser_dockhand_token: ENC[AES256_GCM,data:qqi4+9Yb6v0=,iv:vTeMdw3uqAz/guLTtJN5OAhjXdH5CVfj1cQmZ/tRERM=,tag:tkpaQKf/wG3PzTUnTP2i0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dFJHdXU1SmVJbDFlZ1c5
            SHNIWkV3NlpLVXl5aW16UWlHclFuKzkvVnhZCkhreDBTSW4xMC90TmNjWDF5enpq
            QWJIM21sVDVrZzFDY1F6NXkyb2ZSSHMKLS0tIE85ME5FR2xiV2QvanVEWDVSZit5
            dXQrdTU2TFVad3JDMzYybi9janBMTFUK4JcCoJEqGalUFvKb84Q3SXXvdkXblm+B
            vp57cwHhdo/F5+YW6g2dSqfh52rKhMJ3DqgkCLuSo22T6NLsrFuGsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T16:48:30Z"
    mac: ENC[AES256_GCM,data:H5B6nJyKwNXSkvv6qpoal887mJb/ibS1VhKDtybko9/740u0Vc3ibQVEOx8a39/Tii0R+77Do5RMifqOcayekv/3UVWiJkq9MQll/pHeyaCGf5BIe7ETko/u1MwtTn//63AH+U33yKwfpukuaQ/Fzke70fu+JxegQ5xw1OZFFj4=,iv:gZ5gDBFj8M/TX/ZqpFKRiAHYwHWacYpJZOpW2SXXtyc=,tag:9SmOYKEg20Nt+XRhtC1a5Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
