ansible_host: ENC[AES256_GCM,data:8eLty6vjbS4vEwo=,iv:BAVuj6eg01jCB7q/fdt54rOkT9S/WPC9qqrrJMRnurw=,tag:wB2kHfmxnUPSnAqMpSElWQ==,type:str]
ansible_user: ENC[AES256_GCM,data:zqXQfjE=,iv:DiiWoJcfJxjucUMlEsRnRNGVPlydUU/NEo5T3iy/NAU=,tag:rPA3jrDqbcBowo9ezhbeVw==,type:str]
node_stack_ups_api_user: ENC[AES256_GCM,data:+TE3gY7F,iv:L2BEbRtjz+HsYvxyVQMVexlho3ANQLeeH6MM18nMRUA=,tag:XsWXiRHzGPZGl5d9120lSg==,type:str]
node_stack_ups_api_password: ENC[AES256_GCM,data:Gp5VxeCbo2yXLA==,iv:rPFn03QPlFcfa6DB51/rmXA7+XlnykCTOCeJrPll230=,tag:IxibqBOmANVRr7vlTFxyag==,type:int]
node_stack_obs_host: ENC[AES256_GCM,data:U38f8K0o8EA=,iv:BmC2LTzLRi7dTuKRvKvcKGmBy8YizMMrJUHIspgE7XI=,tag:R1lFEPlqN3X1m6W2Ih9kmg==,type:str]
node_stack_dockhand_url: ENC[AES256_GCM,data:jr05vMnHHKMHp1drEz7zLNB8LM7jrlbFXH7+N2bRP5Pc0DxUphXKzA==,iv:Wr6BJR7JWeIDISPGL51EWqcoss6q68KtY5kT8N0794M=,tag:v+6buL8W+M7CSy4y1/zHoQ==,type:str]
node_stack_dockhand_token: ENC[AES256_GCM,data:m5mt0UvZb09e6IBdss8Eui9BwpVhpGlRo6pQRJ7GotBVgAOJBJiG/NAWxg==,iv:D0325k/gFsg/zEp2/6P1YQkpX8LiD66TpQO76U03zzE=,tag:hYh3cS76uEcwcanyqOVkAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOUNMWWN2RjZ0REJVKzBo
            cU9pRXZCcUlFTjdnc2RuYk15aDk5L1dET2trCms0M0J1NHlIU1p1M1VWbFdMUEZ5
            ZWs2K2tHcHF0MXFtV3VFMUxxSURNKzQKLS0tIHQ3OFR0cUcyRVRMUEgyQytsRVNq
            S1NXRFF6cTdKOUJpY1l4Qkdla1NLWUEKDq/MP7rrde6U4vcrXd6BzDzLOPKQcYtW
            b2YFyqEMNdzplsA6OfHLiGThxCGLNCSSXS4vApMK2VSZAffYaLKztw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-28T16:24:33Z"
    mac: ENC[AES256_GCM,data:5CirKKc7RathGO5kawv23qFlDG4uW1QnPf15bNXnMAwzdzq7F/Kop9d77HCFj1jiyIkeUf+8N8BURZ4abPHycYdvjQ/brRPa364RUGuf7c3gr7bM9FUsCMDEU50WAPB+F1rIp3FKiJwRVBoR7xR/Pb3XlB9quyvFUN3TU+PLqC4=,iv:ZvthI1OQIJraBnHjrWxHg+KKS3kCQB8P3+04bLmFTU8=,tag:mASpgcc1naivlgpRPIF8JQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
