ansible_host: ENC[AES256_GCM,data:hj+X9w14R8lGKks=,iv:K+6xoDw/uMi26HPp0uoiW/He6WLAk/CS+XviYUnHJ64=,tag:llweZoA5uCDpnrFuD42/YQ==,type:str]
ansible_user: ENC[AES256_GCM,data:nS6yO34=,iv:IREZqkrT4Q9y7iY4aCN3K4S4GZTTFmKGWd4w1lgtYr8=,tag:2M6QZj7IYoHLpC7L0W+kRw==,type:str]
hawser_dockhand_url: ENC[AES256_GCM,data:U+Xc3pWRxSru+094NXBljrc2Iig=,iv:7yZA8dqwur7zLejg71Xedjm5TUPKf1IKrCOoI9lY3R0=,tag:JnHzoDXzQnq94matY3wYnw==,type:str]
hawser_dockhand_token: ENC[AES256_GCM,data:MA70XQ/UsFU=,iv:vIR5k2J2o0U89rqV9R8Biti+FuBlEJhH72gLKvmfASQ=,tag:KEkQhNUpWd1y9bnMZ+r3xQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdmFkVTVCSnFHM0orY1dx
            TmtHVDJVWVpwaW9uV2N2MkwxVWhZdmJzNHo0Cm1IRElKK05HaGRxaW8zaHpvNHlo
            N2dzQUJwV0d3WjMwbC9wdVExVGg1cTgKLS0tIDJHREh6TFB3ZEVkTHBKLzNQbzFO
            RCs0Y1RCK2Y3VlpNeVBUZlo3RzR5SXMKGiAaEn6wdP0ady1M9PxkuttnUKHjeW9X
            cb6xt2MdZ8nxz23po4MtHjGIniUzrjibasyczxq6xeMx9lPY4SKJgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T16:48:31Z"
    mac: ENC[AES256_GCM,data:xZNykeZISiUKB83DKY9fP2Rk+ftws8HhRh/ibwPkHfVpK3llyKfq6GVlWjyzkZV068zai++79GoZXFiPQylxR5DQHnWHyhnmHJLMbWi4UWq9Mc121KeJHiP2WPK0EUwSyqwJuqL3jijoAtnkEUfl4C4DpF6XOneZyu4+hWLP094=,iv:oU+SUOZdTVkzgW3ho7P9YVdx3SOv4klq5IOfDMSvys4=,tag:XUc2DKEgh6bNLs+irJ/WMA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
