ansible_host: ENC[AES256_GCM,data:hj+X9w14R8lGKks=,iv:K+6xoDw/uMi26HPp0uoiW/He6WLAk/CS+XviYUnHJ64=,tag:llweZoA5uCDpnrFuD42/YQ==,type:str]
ansible_user: ENC[AES256_GCM,data:nS6yO34=,iv:IREZqkrT4Q9y7iY4aCN3K4S4GZTTFmKGWd4w1lgtYr8=,tag:2M6QZj7IYoHLpC7L0W+kRw==,type:str]
node_stack_obs_host: ENC[AES256_GCM,data:W8JbmVPMjjk=,iv:RTB7/qlZ6skH7QSCsZjLpIdWVfm3d4qUgJNMEZjtf2U=,tag:TG7B8EOnE6Iug8/Kab4K3g==,type:str]
node_stack_dockhand_url: ENC[AES256_GCM,data:dlRBdh0bV0U8QKpkctO2JriAd2c=,iv:fIyylF11l/xDFZVXFNTODX2WpMZ8Sb1xMhmK46jw8ag=,tag:DD4jal5TPoxFn0O+Z+qB3A==,type:str]
node_stack_dockhand_token: ENC[AES256_GCM,data:+culEZ5SCb8=,iv:l/4GD4uKz3+YDPRP1ZgF/6qxTArsP1rsf+XRQeskFrw=,tag:SbAAbCrm2zp7lvFZt5AFhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdmFkVTVCSnFHM0orY1dx
            TmtHVDJVWVpwaW9uV2N2MkwxVWhZdmJzNHo0Cm1IRElKK05HaGRxaW8zaHpvNHlo
            N2dzQUJwV0d3WjMwbC9wdVExVGg1cTgKLS0tIDJHREh6TFB3ZEVkTHBKLzNQbzFO
            RCs0Y1RCK2Y3VlpNeVBUZlo3RzR5SXMKGiAaEn6wdP0ady1M9PxkuttnUKHjeW9X
            cb6xt2MdZ8nxz23po4MtHjGIniUzrjibasyczxq6xeMx9lPY4SKJgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-28T09:18:13Z"
    mac: ENC[AES256_GCM,data:z5gpv7yX40o8x1Fj8fBY6B1Cud5mWpvp8iDx3MoPbDvhyNZ173M1UKGY3O9wYUZf5qPqDI6Pu32UJyiYBJ3+JUCO8jFK9zSVn6i5rxLEEPYn7/ddSgAvlQ1qoTIZLaBzajuMg7u7WYFoKoHHhf7YqoiR8IXoExEnw8cAzHP2JWk=,iv:ismU/Y+7HnnBcQ0ZPYbLLot60N08xb6YpTkIDH/Kxj0=,tag:ytT7MBkoqrOL0bO2Edghtg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
