# Bootstrap
# hostname_enabled: true

# Shell
# motd_enabled: true
# dotfiles_enabled: true

# Unattended upgrades
unattended_upgrades_enabled: true
unattended_upgrades_skip_reboot_required: true
unattended_upgrades_blacklist:
  - "docker-ce"
  - "docker-ce-cli"
  - "containerd.io"
  - "wireguard*"
  - "iptables*"
  - "nftables*"
  - "netfilter*"
  - "iproute2"
  - "bridge-utils"
# unattended_upgrades_auto_reboot: false
# unattended_upgrades_auto_reboot_time: "04:00"

# Swap
# swap_enabled: false
# swap_size: "2G"

# Firewall
# ufw_enabled: false
# ufw_extra_rules:
#   - { rule: allow, port: 8080, proto: tcp, comment: "Web" }

# Docker
# docker_enabled: true

# Cron
# cron_enabled: true
# cron_docker_prune: true
# cron_extra_jobs: []

# UPS
# ups_client_enabled: false

# Node agent
node_stack_alloy_enabled: false
node_stack_hawser_enabled: false
node_stack_bifrost_enabled: false
node_stack_backrest_enabled: false
