ansible_host: "CHANGEME"
ansible_user: "CHANGEME"
hawser_dockhand_url: "http://CHANGEME:9000"
hawser_dockhand_token: "CHANGEME"
bifrost_private_key: "CHANGEME"
bifrost_address: "10.13.13.X/32"
bifrost_peer_public_key: "CHANGEME"
bifrost_peer_endpoint: "vpn.example.com:51820"
