ansible_host: "CHANGEME"
ansible_user: "CHANGEME"
node_stack_obs_host: "CHANGEME"
node_stack_dockhand_url: "http://CHANGEME:9000"
node_stack_dockhand_token: "CHANGEME"
node_stack_ups_api_user: "CHANGEME"
node_stack_ups_api_password: "CHANGEME"
node_stack_backrest_discord_webhook: ""
