ansible_host: ENC[AES256_GCM,data:j5fzUbuTChFPgFo=,iv:9fUltoAguu6+pG1Qysk8n2EZ8283E95oveiYM107D+E=,tag:oUwteUsnXnngojad+MKBNA==,type:str]
ansible_user: ENC[AES256_GCM,data:J21CcbI=,iv:g3uo10Ee0rnPVeJJKsHqh5PRcVvVGEpa0NKoOWxGqnA=,tag:cAMBjwc+M2XycvSlpH1ekQ==,type:str]
node_agent_obs_host: ENC[AES256_GCM,data:TgyFgdaCTgY=,iv:NB7CYf8HjAtTtb9mN0XOdaFaAkV71j1J6+Ff3vdoJr8=,tag:J/OAczfIez5NwK8DbxUrSg==,type:str]
node_agent_dockhand_url: ENC[AES256_GCM,data:KZqYpIOkQh/sr6oldGPecGMyl18=,iv:Q7ZeRSUhuh3Ds8M+zsjuudj7xXv5B1G6Lv7s39GgYZ0=,tag:MRQ3TZ9YCgOJUmfo0s2tEw==,type:str]
node_agent_dockhand_token: ENC[AES256_GCM,data:J5My0Zm/oVc=,iv:vBL4XEuoglddKw3fcqcnEu8stodKL4oX2eJg/ik7fp4=,tag:u+jC1lVXU+MbcTdtCg0g1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMXNXbGcvRER3U1p1RWdy
            emgzaHN5UEtnUDVuSWpLakRPMk1NRnJwNEhVCmVYU0haemgzWEFEcm94dG1BRElp
            UmlmL2RkN3lGMnJ3am9NMzI2b2IxekUKLS0tIHdaOU5hL2ZFL3hOYmpTNmdrcmtk
            RWdiaTNTVW14SG16SDhrYmpHUzhSWjQKHohLuuCGItXf33j7jTumaWp4GZglKPL9
            nYPup3bEpAR3DvwFtvJc7Ldu1fsemACFximGbtbsVx2RnD1fQpM4bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-27T18:40:09Z"
    mac: ENC[AES256_GCM,data:bZwqmd3UkCWKRqS5X66SGhvcpr9AMHF6SK+4NVk/5PNLu8zYGL90HaNtEUHdk6bqaxrt7TvYVc4NLWYtS1AClZYH3yEg8TLTWOXf3e6rn90yzx9CU4KELQTV8YagB8yXo2Kb9tKyu7Yg4UHlHwfMaCRqXKoUhvk7f/p1pou1QEI=,iv:EvkuJXpXFnSm8dmSFrvgiDAqvfkbD442rV17FfqkZaA=,tag:/UARbTBtYZ4bkBcFOucmdQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
