ansible_host: ENC[AES256_GCM,data:rQy96mrJYpG/PP0=,iv:graVETNbcOIaaLa5qr+ng3gD3as6Pl9iQQDwUX9SmTI=,tag:V6hVe2ZwEFknrVQjTSCv4A==,type:str]
ansible_user: ENC[AES256_GCM,data:uV7XM7U=,iv:iQOP/rYSvNUK3HWzgJlk2zzBhy+OTHpYVnzsX3FlVEw=,tag:phNgW6JipPrE/VgucS+IGA==,type:str]
node_stack_obs_host: ENC[AES256_GCM,data:s8Yw38I02ws=,iv:zppa24hc41xHDijVqoZZNsK+Cwzm/PLk8x3KsGRXf9Q=,tag:A9sPd0KtbNNG4yKjMbAZ+Q==,type:str]
node_stack_dockhand_url: ENC[AES256_GCM,data:M1y+kMi08ZOvCjTL6OCYiNA6gvY=,iv:UIZdw+sgO5SHBvzjGVJvH+XHSKSUEIuu6VrPUITMxno=,tag:auxRbdjOYQ2+yXhHj/Uj0w==,type:str]
node_stack_dockhand_token: ENC[AES256_GCM,data:Xsp37q88rcY=,iv:F2xyFKO+1cSRipWc3wSbxpaVd+1HE24lbPB6im4ehhs=,tag:84ZYy4p827EgfxTej0Gr5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlm8qzcj0wmn063uq00s7vzfne0wkd66ft4szphr4l6mz7k2ssaqpxpf8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdnR1eVVjWXFvbXFUckpj
            WEl3UmxoK3ZiS1BnQ0plN285MVBtQlRoYmhNCjNXbkpVQ1dOOExDUGtxdGNyTStB
            MmkyblJoRHJoTkpwRStuZHlnL3NONXcKLS0tIGhyM2NlWkxxOERiUkZBMjZsbDI2
            akJ5TVE2R3VqRlJ1eitCNVNJL2ZDVTgKzNXH1dohrU5PUh37mkqNovVAJ8W2SUib
            mwG56eRs/igIiWL+4mREV/r++6JsdaIKXk7mInu5g9Qe6WkCRnEP1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-28T09:18:13Z"
    mac: ENC[AES256_GCM,data:lqK/w9R56RBbvlk/XKqehXQfAM3/nUYZMuZ+HA4f4TOX3O1pCyCeOvNGZQaAeKYVP/5EkrraH6YusYnvFUxzKKA2tMcfc7odfpe69cxet2z8Sf/IsJ6kXO5Msx0Ocz3VpmspsyL8ETW24GH1c+hTlA+30UnkzA/JraXJalBNgAk=,iv:kmVY6seWUpkqvvWdUrEexIq7coTCF+BAVoxw2ysDs/0=,tag:Kp2P4kCYRWhRkMvapbhV7g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
